### ISSUE TITLE
Add Luri Bakhtiari language to app

### ISSUE THREAD

**Issue by hosseinabaspanah** [patzly/doodle-android#100]
80% of Luri Bakhtiari language has been translated, but it has not yet been published...
Is there a special reason???

**Comment by hosseinabaspanah** [comment]
I will try to do it as soon as possible, but please don't forget to add it...

**Comment by patzly** [comment]
It works automatically and will be included in the next release, but a release simply needs time because I have not much free time.

**Comment by patzly** [comment]
Implemented in e2a2227be9557c9fd03b6c9b0c0cdb748577759f, but please complete your translation as we have discussed in the other issue. Thanks!

**Comment by hosseinabaspanah** [comment]
Hello, as I promised, I translated Doodle 100% to Luri Bakhtiari...

I hope you will be satisfied with me as a committed lur...
@patzly
