### ISSUE TITLE
Reset all settings button does not work

### ISSUE THREAD

**Issue by D15A-Jai-61** [patzly/doodle-android#104]
**Describe the bug**

I want to stop using live wallpapers due to another bug I reported in another issue.

The "Reset all settings" button in the "Other options" section seems to work at first, as the wallpaper changes after clicking it, but wallpapers still keep changing automatically which I don't want.

I want the wallpapers to be static like they were originally and how they are by default, I don't want them to keep changing everyday after a certain amount of time, especially since it takes random images from my gallery and sets it as my wallpaper.

**To Reproduce**

1. Go to Other options
2. Click on Reset all settings
3. See wallpaper change to default or any image from gallery, reboot as it says in the app, wait for a certain number of hours or minutes till it automatically changes to another image in the gallery.

**Expected behavior**
After clicking Reset all settings and rebooting, my wallpaper should never change unless I change it manually.

**Screenshots**

Not Applicable 

**Usage information (please complete the following):**

 - Device: Nothing Phone 2a
 - OS: Android 14 (Nothing OS 2.6)
 - App version: 5.6.1

**Logcat copied from "Other options"**

--------- beginning of main
09-09 17:26:23.595 16426 16447 E OpenGLRenderer: Unable to match the desired swap behavior.
09-09 17:26:38.645 16426 16447 E OpenGLRenderer: Unable to match the desired swap behavior.

**Comment by patzly** [comment]
As I commented in your other issue, this behavior is from your phone, not caused by Doodle. If you don't see a wallpaper you selected in Doodle, then the Doodle wallpaper engine is not running. For you it's because it crashes, so your system simply uses its own wallpapers. If you keep seeing random photos, you have to change some settings of your phone, not in Doodle.

**Comment by D15A-Jai-61** [comment]
@patzly 

I did not share a logcat here for so long because I did not plan on using the app again.
If I decide on reusing the app and then resetting my phone, then I may send the logcat.
