### ISSUE TITLE
The & is not correctly shown

### ISSUE THREAD

**Issue by Benkralex** [patzly/doodle-android#108]
**Describe the bug**
The '&' is shown as HTML-Code ('&amp;')

**To Reproduce**
1. Installed on Google Pixel 8
2. Opened App

**Expected behavior**
The '&' should be shown as Text '&'

**Screenshots**
![Screenshot.png](https://github.com/user-attachments/assets/d12b471a-2489-4dd9-883e-efe554c871f8)

**Usage information:**
 - Device: Google Pixel 8
 - OS: Android 15
 - Version 6.0.0

**Comment by patzly** [comment]
Thank you so much for reporting! Didn't see that before publishing.
