### ISSUE TITLE
Inclusion in F-Droid

### ISSUE THREAD

**Issue by tentacleuno** [patzly/doodle-android#11]
Would you consider putting this app on F-Droid, please?

Thank you,
Tentacles.

**Comment by patzly** [comment]
Hi, yes that's possible! But my brother and I learned when adding [Grocy Android](https://github.com/patzly/grocy-android/) to F-Droid that the whole process is a bit complicated and takes time.
In the meantime, please be patient and watch this repository to be notified of new releases.

**Comment by shuvashish76** [comment]
https://gitlab.com/IzzyOnDroid/repo/-/issues/193

Thanks to @IzzySoft the app is now available on Izzy repo.
https://apt.izzysoft.de/fdroid/index/apk/xyz.zedler.patrick.doodle

---

& requested for F-Droid inclusion: https://gitlab.com/fdroid/rfp/-/issues/1870

**Comment by patzly** [comment]
Thank you so much! Can you tell me what I have to do next to include Doodle in the official F-Droid store?

**Comment by patzly** [comment]
Doodle Android is now available on F-Droid! Thank you so much for your help @IzzySoft !

**Comment by IzzySoft** [comment]
Gladly done! I'll remove it from my repo then after the usual overlap of about 10 days (unless you insist I should keep it).
