### ISSUE TITLE
Feature request: option to change background color

### ISSUE THREAD

**Issue by Hmmmmmmmmmm** [patzly/doodle-android#31]
As all Pixel/android lovers all know, Google has built a color extract engine "monet" in the upcoming android 12, which does a amazing job generating theme colors based on any custom wallpapers. This app has done a great job working with "material you" color system, but sometimes the extracted color may not look so perfect with the doodle itself.

So i was wondering if devs can add an option to manually change the background/foreground color, just in case someone being not satisfact by the whole look. Any further details/devs are welcomed!

**Comment by Hmmmmmmmmmm** [comment]
Sorry for the late reply :P

I figure i can run tests of Monet engine with Doodle using the [official android 12 easter egg widget](https://9to5google.com/2021/09/08/android-12-easter-egg-widget/). I've tried 2 of (my fav) doodle live wallpapers and make screenshots of the subtracted color , you can read the exact RGB color using any screen reader tool. I think android would use the one marked "A1-100" as system theme color (as used in themed icons for 1st-party apps).

![image](https://user-images.githubusercontent.com/28838634/139781046-b42cf032-e26b-40d0-a58f-021c15dc368c.png)


The thing is, the monet engine is quite buggy right now and you can choose more than one color palettes from the same wallpaper, idk if it has something to do with the fixed 3 colors you mentioned earlier. I hope this would help you, and looking forward for your future dev!

**Comment by patzly** [comment]
@Hmmmmmmmmmm Thank you for your helpful screenshots! I will release a big update with full Material You integration very soon :)
Do you like to test a prerelease? I would only release it on GitHub, so you can download it and give feedback here in this issue.
One new feature is an option to select the primary, secondary and tertiary colors from all available colors of a wallpaper! But there are many more changes regarding theming where I would like to receive some feedback of an Android 12 Pixel user before the full release.

**Comment by Hmmmmmmmmmm** [comment]
@patzly I'm more than willing to test! Looking forward for that release soon~ :)

**Comment by patzly** [comment]
@Hmmmmmmmmmm Thank you so much! I have published a test release [here](https://github.com/patzly/doodle-android/releases/tag/v4.3.0-beta1). Could you please check it carefully if everything is fine? You can look at the following changes:
- Material You app theming and look
- Language selection
- Extracted colors selection (full color range of the wallpaper is only implemented in the first Doodle collection wallpaper (black variant) and in the Leafy wallpaper by Anna Kövecses, I will add all colors for all wallpapers before the main release)
- instant changing of settings (when an option is changed the wallpaper is notified in the background to rerender, theme changes should therefore be smoother than before)

The most important part is the dynamic app theming: if you change the wallpaper in the app, the running Doodle wallpaper service is notified in the background and changes the wallpaper, also it notifies the system that the wallpaper colors have changed. So it should result in the change of the app theming colors to the current wallpaper (main) colors, without leaving the app (and therefore without visiting the homescreen). Hopefully it works, I can't test it myself! Maybe you could make a screen recording for me when it works :)

I heard that the calculation of new theme colors requires a lot of CPU and that the phone laggs if an automatization app changes the wallpaper every 10 seconds or faster (reported by Android Police). Does your phone also lag if you change the wallpaper in Doodle?

**Comment by patzly** [comment]
Now I fully implemented options to change the "extracted" colors and other Android 12 improvements, hope this improves your experience! Sadly a wallpaper service restart is required on Android 12 every time the colors change to apply them again to the system's theming engine... There is no workaround for this, simply notifying the system that the colors have changed doesn't work like on previous Android versions anymore.
