### ISSUE TITLE
Why you removed the zoom in & out effects of the wallpaper when opening app drawer? That was good

### ISSUE THREAD

**Issue by Unmesh98** [patzly/doodle-android#34]
The question is in the name of the issue only.
And another one
A kind of request 
Can u make zoom out of wallpaper effect work when we open notification pannel or go to homescreen from a app ?

**Comment by patzly** [comment]
Hi! So to answer your question: this behavior is intended by Samsung on your phone😬
I saw under your review that you have a Samsung phone, and with an update to One UI and/or their launcher TouchWiz they removed all the effects introduced with Android 11.
I have Android 11 Pixel Experience installed on my current phone (although I'm currently waiting for a brand new Pixel 6) and there are all the effects you are missing: app drawer zoom, notification panel zoom and zoom when returning to home screen.
I didn't remove anything from the app, you can try to reset all options in the "Other options" section if you accidentally turned a zoom option off, but on my Samsung tablet all the zoom effects were missing, too...
The only working zoom effect is on lock screen because this is rendered by Doodle itself, all others rely on system callbacks which can be turned off by Samsung and co. Sorry to dissappoint you!

**Comment by Unmesh98** [comment]
Bro then me ded.
Samsung shit. Continue your good work bro 👏
Hey I got an suggestion ☺
Can you add pixel 6 plants bloom wallpapers to doodle ?
They are good 👍

**Comment by patzly** [comment]
@Unmesh98 Yes Samsung does not a good job when it comes to adopt features from stock Android...

I will not include the bloom wallpapers in Doodle, as these are not doodle-like and simple static photos where I can't implement parallax effect.
...But(!): Now I own a Pixel 6! And I am not satisfied with the plant wallpapers there (they are scrolling to much and no dark/light change)
So I will make a new app called Bloom where we can select these wallpapers and I will implement auto-system dark mode and optional horizontal scrolling and tilt effect! Also on the original bright versions the text is white, that's a "bug" of Android 12 I think, but I can configure that in the new app.
Bloom won't be available on Google Play (only on GitHub) because the copyright question is obvious for the photos and I don't want to have a conflict with Google...

**Comment by Unmesh98** [comment]
Patrick Zedler
@Unmesh98 Yes Samsung does not a good job when it comes to adopt features from stock Android... I will not include the bloom wallpapers in Doodle, as these are not doodle-like and simple static photos where I can't implement parallax effect. ...But(!): Now I own a Pixel 6! And I am not satisfied with the plant wallpapers there (they are scrolling to much and no dark/light change) So I will make a new app called Bloom where we can select these wallpapers and I will implement auto-system dark mode and optional horizontal scrolling and tilt effect! Also on the original bright versions the text is white, that's a "bug" of Android 12 I think, but I can configure that in the new app. Bloom won't be available on Google Play (only on GitHub) because the copyright question is obvious for the photos and I don't want to have a conflict with Google...
Awesome Awesome Awesome

[U N M E S H - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=1d0ifb)	[1d0ifb]

On December 30, 2021 at 1:42 GMT, Patrick Zedler ***@***.***> wrote:

***@***.***(https://github.com/Unmesh98) Yes Samsung does not a good job when it comes to adopt features from stock Android...

I will not include the bloom wallpapers in Doodle, as these are not doodle-like and simple static photos where I can't implement parallax effect.
...But(!): Now I own a Pixel 6! And I am not satisfied with the plant wallpapers there (they are scrolling to much and no dark/light change)
So I will make a new app called Bloom where we can select these wallpapers and I will implement auto-system dark mode and optional horizontal scrolling and tilt effect! Also on the original bright versions the text is white, that's a "bug" of Android 12 I think, but I can configure that in the new app.
Bloom won't be available on Google Play (only on GitHub) because the copyright question is obvious for the photos and I don't want to have a conflict with Google...

**Comment by Unmesh98** [comment]
Patrick Zedler
@Unmesh98 Yes Samsung does not a good job when it comes to adopt features from stock Android... I will not include the bloom wallpapers in Doodle, as these are not doodle-like and simple static photos where I can't implement parallax effect. ...But(!): Now I own a Pixel 6! And I am not satisfied with the plant wallpapers there (they are scrolling to much and no dark/light change) So I will make a new app called Bloom where we can select these wallpapers and I will implement auto-system dark mode and optional horizontal scrolling and tilt effect! Also on the original bright versions the text is white, that's a "bug" of Android 12 I think, but I can configure that in the new app. Bloom won't be available on Google Play (only on GitHub) because the copyright question is obvious for the photos and I don't want to have a conflict with Google...
And brother,
Zoom effects, parallax effects are working again in one ui 3.1

😄😄🥳🥳

[U N M E S H - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=1d0iht)	[1d0iht]

On December 30, 2021 at 1:42 GMT, Patrick Zedler ***@***.***> wrote:

***@***.***(https://github.com/Unmesh98) Yes Samsung does not a good job when it comes to adopt features from stock Android...

I will not include the bloom wallpapers in Doodle, as these are not doodle-like and simple static photos where I can't implement parallax effect.
...But(!): Now I own a Pixel 6! And I am not satisfied with the plant wallpapers there (they are scrolling to much and no dark/light change)
So I will make a new app called Bloom where we can select these wallpapers and I will implement auto-system dark mode and optional horizontal scrolling and tilt effect! Also on the original bright versions the text is white, that's a "bug" of Android 12 I think, but I can configure that in the new app.
Bloom won't be available on Google Play (only on GitHub) because the copyright question is obvious for the photos and I don't want to have a conflict with Google...

**Comment by Unmesh98** [comment]
Patrick Zedler
@Unmesh98 Yes Samsung does not a good job when it comes to adopt features from stock Android... I will not include the bloom wallpapers in Doodle, as these are not doodle-like and simple static photos where I can't implement parallax effect. ...But(!): Now I own a Pixel 6! And I am not satisfied with the plant wallpapers there (they are scrolling to much and no dark/light change) So I will make a new app called Bloom where we can select these wallpapers and I will implement auto-system dark mode and optional horizontal scrolling and tilt effect! Also on the original bright versions the text is white, that's a "bug" of Android 12 I think, but I can configure that in the new app. Bloom won't be available on Google Play (only on GitHub) because the copyright question is obvious for the photos and I don't want to have a conflict with Google...
But wen starting bloom project?
Me eagerly waiting 😘😘

[U N M E S H - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=1d0ik5)	[1d0ik5]

On December 30, 2021 at 1:42 GMT, Patrick Zedler ***@***.***> wrote:

***@***.***(https://github.com/Unmesh98) Yes Samsung does not a good job when it comes to adopt features from stock Android...

I will not include the bloom wallpapers in Doodle, as these are not doodle-like and simple static photos where I can't implement parallax effect.
...But(!): Now I own a Pixel 6! And I am not satisfied with the plant wallpapers there (they are scrolling to much and no dark/light change)
So I will make a new app called Bloom where we can select these wallpapers and I will implement auto-system dark mode and optional horizontal scrolling and tilt effect! Also on the original bright versions the text is white, that's a "bug" of Android 12 I think, but I can configure that in the new app.
Bloom won't be available on Google Play (only on GitHub) because the copyright question is obvious for the photos and I don't want to have a conflict with Google...

**Comment by patzly** [comment]
As soon as I have time, now I have to learn for my exams👍🏼

**Comment by Unmesh98** [comment]
Oh no problem then
Best of luck bro for ur exams

[U N M E S H - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=1d29qq)	[1d29qq]

On January 2, 2022 at 5:11 GMT, Patrick Zedler ***@***.***> wrote:

As soon as I have time, now I have to learn for my exams👍🏼

**Comment by patzly** [comment]
Thanks!
