### ISSUE TITLE
Unstable size and position

### ISSUE THREAD

**Issue by Gero8389** [patzly/doodle-android#37]
Every time I unlock the phone, the shapes of the wallpapers appear at different angles and sizes. Sometimes the wallpaper is too small or it gets stuck in weird shapes. Apparently this has to do with the zoom effect when unlocking the device. I'm running Android 9.

**Comment by patzly** [comment]
Hi, could you please send a screen recording where I can see the problem? I think you can simply upload a video here.

**Comment by Gero8389** [comment]
My screen recorder stops when I lock the phone so I can't record the unlocking process, but here I upload some screenshots of how the wallpaper looks after unlocking the screen several times.  As you can see, each time the wallpaper looks different. You can take the search bar widget as a reference. Maybe it is just a problem with my device and not a general problem.

![Screenshot_20211229_232437](https://user-images.githubusercontent.com/96814426/147717346-1db8abbc-477c-4941-bd3a-efddb478cfbf.jpg)
![Screenshot_20211229_232447](https://user-images.githubusercontent.com/96814426/147717348-234b9a99-a3cf-4b81-8108-2588e58724a6.jpg)
![Screenshot_20211229_232526](https://user-images.githubusercontent.com/96814426/147717350-b93d2100-9a7e-42d8-bfb7-9f4a9dc4324f.jpg)
![Screenshot_20211229_232542](https://user-images.githubusercontent.com/96814426/147717351-882d3dd2-55f8-42df-8e36-51cb63f0081b.jpg)

**Comment by patzly** [comment]
That's weird... Does the unlock animation occur? Does it animate until you are on homescreen? A screen recording of the problem would be so helpful😄 Wouldn't it be possible to record your screen with another device?
Also what happens if you turn off lockscreen zoom?

**Comment by Gero8389** [comment]
This was fixed with yesterday's update (5.1.0), now all works perfectly!

**Comment by patzly** [comment]
That's really great!! Although I don't know what I changed in the update regarding lockscreen zoom :D
Hopefully it keeps working! Else you could reopen this issue. Thanks!
