### ISSUE TITLE
Jerky zoom animation when tilt effect is turned on

### ISSUE THREAD

**Issue by patzly** [patzly/doodle-android#42]
Maybe caused by frame drawing in `WallpaperService` or in `SvgDrawable`

**Comment by patzly** [comment]
Do you mean that you rotated your device and the tilt effect was smooth but the wrong direction? Or maybe was it in combination with zoom effect that much laggy and slow responding that you though it was inverted?

**Comment by coxackie** [comment]
@patzly it was the former -  tilt effect was smooth but the wrong direction. It happened couple of times a week or so ago, but I have not noticed it lately. If it reappears, I will let you know.
