### ISSUE TITLE
A dracula / purplish variant.

### ISSUE THREAD

**Issue by scientiac** [patzly/doodle-android#46]
A dracula themed or purpulish doodle of pixel 4 walls would be very nice to have.

**Comment by patzly** [comment]
Do you mean colors similar to the first variant of the third Pixel 4 wallpaper? That's kinda purple I think.

**Comment by scientiac** [comment]
Nooo, it's too bright in some parts. Check this site you will get the color palettes. 
https://draculatheme.com/contribute
