### ISSUE TITLE
Random wallpaper based on time duration or days 

### ISSUE THREAD

**Issue by gabey14** [patzly/doodle-android#47]
Random wallpaper based on time duration or days would be a better feature than on every time we lock the phone anything similar to what I mentioned if possible would be great. Lastly thanks for this wonderful app and keep doing the great work👍.

**Comment by patzly** [comment]
That's a nice idea, I will implement that as soon as I have enough time. Thank you for your big compliment!

**Comment by gabey14** [comment]
@patzly Thanks buddy for implementing this. Hope to try it out soon 😄.

**Comment by patzly** [comment]
Thank you! Took the whole day and night 😆 
The update will be ready today!
