### ISSUE TITLE
What about bloom walls ?

### ISSUE THREAD

**Issue by Unmesh98** [patzly/doodle-android#49]
U can close this issue.. but what about bloom walls ? Wen making them ? 😅😅

**Comment by thenoobcoderlol** [comment]
I would love to see that missing Pixel 6 wallpaper, I'll send an attachment 
![Uploading Google Pixel 6 leaked wallpapers (6).png…]()

**Comment by patzly** [comment]
@Unmesh98 I have my exams in about two weeks, so I currently have no time for development :)
In mid-February I will take a look into an important bug in Doodle and start implementation of Material 3 in Stiefo, another app by me. As soon as I have time I will start Bloom, but starting a completely new project is always a big task. Until then you and I can use either Doodle or the static Bloom wallpapers :)
