### ISSUE TITLE
Doesn't work on MIUI 

### ISSUE THREAD

**Issue by ShoreNinth** [patzly/doodle-android#56]
![-189f801ccca6216d.jpg](https://user-images.githubusercontent.com/54047776/169295727-ca87d568-1c8d-4711-be51-c8de23de2a63.jpg)

**Comment by patzly** [comment]
Please attach screenshots in English next time, I didn't made the Chinese translation of the app.
The error message means that your device doesn't have a live wallpaper picker installed, or Doodle could not find a system live wallpaper picker to open.
You can try to install the app Google Wallpapers on your phone, scroll down to live wallpapers and try to apply Doodle from there. If that also doesn't work, please google the problem "MIUI live wallpaper picker not available" or something similar to find a possible solution. It's a common problem of MIUI that it doesn't work well with live wallpapers.
