### ISSUE TITLE
Issues with MIUI & moving (live) wallpapers

### ISSUE THREAD

**Issue by IdahoODaniels** [patzly/doodle-android#59]
Im currently using MIUI 12, and what I want is the moving wallpaper (when you move your phone). However, I'm running into these issues:

> I set it my wallpaper from the app.

> After one minute of inactivity on my device, it turns into a still image.

> It works when I restart my phone or restart the app, but as mentioned above it works temporarily and turns into a still image after one minute (exactly).

I've tried everything- setting it from the Google Wallpaper app (has no effect), clearing my Themes app data, and making sure the app has full permissions and can bypass battery saver. Is this app (or the moving wallpaper) not compatible with MIUI 12?

Thanks.

**Comment by IdahoODaniels** [comment]
I've found a temporary solution. I've seen this issue, but not with a one minute timer, even with the app open.

**Comment by patzly** [comment]
@IdahoODaniels Hi, I've heard of this before, the problems seem to be always caused by MIUI and its battery management. For me as developer there is nothing I can do against that, the movement is managed by a simple broadcast receiver and this should work without problems, it's just the official way... But I'm glad that you've found a solution, can you tell me what you did?

**Comment by IdahoODaniels** [comment]
I used a third party to hide the app, It seems to fix the one minute timer and I do not have to worry about accidentally closing the app (after restarting my phone).

Unnefficient, but it works.

**Comment by patzly** [comment]
I can't fully understand this because I have never set a timer anywhere, I don't know why it's one minute or why it stops moving at all, it's very weird :D

**Comment by IdahoODaniels** [comment]
I believe this is more on MIUI's side. There may be a timer to stop running apps automatically?

Also, I was reading your response to another post. When I try setting Doodle as a default live wallpaper app in Themes,   Doodle just doesn't show up. Same case with Google's wallpaper app.

**Comment by IdahoODaniels** [comment]
It shows on Google's Wallpaper app, but doesn't exactly do anything when I click it. It opens a window and immediately closes.

Apologies for not being clear. I'm starting to suspect this is due to my aging phone.

**Comment by patzly** [comment]
I think this issue is a duplicate of #41 as both have to do with MIUI background processes. I will close this now and copy the important information from you into #41. Thanks!
