### ISSUE TITLE
Feature Request: Custom Monet Colors

### ISSUE THREAD

**Issue by Jacocococo** [patzly/doodle-android#60]
I just found this app and immediately loved it, but there was just one very small thing that missed.

I was a fan of the Material You color scheme that my old wallpaper had and wanted to keep it, but I couldn't find a way to choose colors other than the hardcoded ones.

I ended up just changing the hex codes and compiling from source to get the colors to my likings, but even though it kind of breaks the idea of Material You I still think it would be a nice feature to have built in without needing to do a custom compile.

**Comment by patzly** [comment]
Thank you! As you might have noticed during editing, it would be hard to move the color codes away from the wallpaper variant classes.. This feature would require a preference stored for each color of each wallpaper variant and a new color picker dialog and so on, maybe I have time for all this in the future.

**Comment by HiFiiDev** [comment]
I wish I was smarter so I could help 😂

**Comment by patzly** [comment]
Thanks to @Jacocococo for your work! I removed the lib because it is not compatible with Material 3, instead I made my own color selection dialog (took several days...). Your work helped me a lot!
