### ISSUE TITLE
Force white text doesn't work on Pixel 6 Android 12L

### ISSUE THREAD

**Issue by LilCuteli** [patzly/doodle-android#61]
Hello, the _Force White Text_ option in the _Appearance_ section of the app doesn't work.

**Comment by patzly** [comment]
Thanks, I couldn't reproduce it yet, but I already realized that this option only makes sense for older Android versions. I will rename the option to _Force **dark** text_ on Android 12.

**Comment by patzly** [comment]
Can you please provide more information on how I can reproduce this problem?

**Comment by patzly** [comment]
I tweaked the toggle logic for the launcher text color preference for the next version, then it shoud behave more intentionally.
