### ISSUE TITLE
Optional zoom-out animation instead of zoom-in

### ISSUE THREAD

**Issue by Seandylan123** [patzly/doodle-android#66]
I really don't like the zoom in animation when you unlock your phone if this was added i could like unlocking my phone

**Comment by patzly** [comment]
I don't really understand what you mean, the zoom-in animation is one of the main features of the app. If you don't like it you always have the possibility to customize the animation duration or to disable it entirely.

**Comment by Seandylan123** [comment]
> I don't really understand what you mean, the zoom-in animation is one of the main features of the app. If you don't like it you always have the possibility to customize the animation duration or to disable it entirely.

Well the pixel 4 really has a different animation when unlocking your phone for the wallpaper animation there should be a option to change the animations when unlocking your phone if you select any of the pixel 4 doodle collection

**Comment by Seandylan123** [comment]
> If you say "to change the animation" you can't expect at all that I know what animation you want🤷🏻‍♂️ If you want "another animation" you have to describe it or provide a screen recording so that I know what you mean. Currently I would say that even on the Pixel 4 another animation than simply zooming in doesn't make sense. As I said, you can make it faster or slower in settings if you mean that it's just faster or slower on Pixel 4.


https://user-images.githubusercontent.com/106500241/188087361-0eb26807-74f2-4242-ad4e-a97137c0fede.mp4
Here's example of the animation

**Comment by patzly** [comment]
Ah you mean the animations of the original Pixel 4 Doodle wallpapers after the user changes the style.
As the description of this project says, this app is not just a copy of the original wallpapers, it's an entirely different approach. So this animation is simply not possible with the rendering engine I wrote for this app.
Also I don't understand why your messages (especially your first comment) are so rude, if you know the original Pixel 4 wallpapers you should also know that this kind of animation is only happening **a single time** after you change the design durong wallpaper configuration. All the other times when you unlock your phone and so on even the original Pixel 4 wallpapers simply zoom. So there is no need for you to blame my project if the thing you are referring to is not different in the point you complain.

**Comment by Seandylan123** [comment]
> Ah you mean the animations of the original Pixel 4 Doodle wallpapers after the user changes the style. As the description of this project says, this app is not just a copy of the original wallpapers, it's an entirely different approach. So this animation is simply not possible with the rendering engine I wrote for this app. Also I don't understand why your messages (especially your first comment) are so rude, if you know the original Pixel 4 wallpapers you should also know that **this kind of animation is only happening a single time after you change the design during wallpaper configuration**. All the other times when you unlock your phone and so on even the original Pixel 4 wallpapers simply zoom. So there is no need for you to blame my project if the thing you are referring to is not different in the point you complain.

Ok I'm closing this issue for now
