### ISSUE TITLE
Wallpaper is changed when dark mode is activated 

### ISSUE THREAD

**Issue by MrVoid23** [patzly/doodle-android#67]
I have my dark mode set to a specific time of the day.Same behavior when I've set it on sunset and sunrise.When dark mode turns on,the wallpaper automatically changes.This is really annoying,when using the new feature that sets wallpaper at a specific time of the day.

**Usage information (please complete the following):**
 - Device: Poco F3 using a custom rom(Arrow Os)
 - OS:12.1
 - Version [e.g. 5.5.0]
https://user-images.githubusercontent.com/106260709/186214133-dc135508-0463-4ba8-9ff5-f4a47b763298.mp4

**Comment by MrVoid23** [comment]
Also happens when using random wallpaper everytime screen is turned off.

**Comment by patzly** [comment]
Oh that's right, thanks for reporting that! I will fix it in a bug fix release today or tomorrow.

**Comment by patzly** [comment]
Fixed in commit 2765f61253e4b97451294083ab76b7a5efc000f9.
