### ISSUE TITLE
Monet color engine does not change system accent color

### ISSUE THREAD

**Issue by Dafelleant** [patzly/doodle-android#69]
While live wallpapers active, system uses only one color "blue". 

**To Reproduce**
Select any wallpaper and see if system accent color changed or not 

**Expected behavior**
Colors should match current wallpaper

**Screenshots**

![Screenshot_20220826-124738_Doodle](https://user-images.githubusercontent.com/23417749/186877726-ea7e84d2-e2af-410c-bef0-4f0178a820f8.png)
![Screenshot_20220826-124742_Trebuchet](https://user-images.githubusercontent.com/23417749/186877736-be409c73-55bc-4a9f-a1cd-7cb76cb6c948.png)
![Screenshot_20220826-124746_Trebuchet](https://user-images.githubusercontent.com/23417749/186877738-bee2bc66-b126-47bd-9093-404257dc72ba.png)
![Screenshot_20220826-124751_Android S Easter Egg](https://user-images.githubusercontent.com/23417749/186877741-caf82557-5980-43af-b269-c240f1e2d035.png)

**Usage information**
 - Device: [OnePlus 6T]
 - OS: [ Android 12 L]
 - Version [ 5.5.0]

**Comment by Dafelleant** [comment]
Another thing I noticed is when you select Night Mode Off system accent will be locked to 'brownish' instead of blue.

![Screenshot_20220826-130536_Doodle~2](https://user-images.githubusercontent.com/23417749/186881254-8b6dea34-463e-4c7a-9147-c54ad810c790.png)
![Screenshot_20220826-130603_Trebuchet](https://user-images.githubusercontent.com/23417749/186881257-dd75eaaa-f8b3-4394-9692-3a5d37ddddde.png)
![Screenshot_20220826-130607_Android S Easter Egg](https://user-images.githubusercontent.com/23417749/186881260-46a1be80-9a2f-4304-b9c4-4fabd0edf95d.png)

**Comment by Dafelleant** [comment]
Okay, entering Wallpaper & Style from home screen breaks color change and forces wallpaper being randomized.

**Comment by patzly** [comment]
Thanks, that seems like multiple different issues. All in all I can say that the issues are caused by buggy customizations made by OnePlus to the original monet engine. A developer has exactly one official way to let the system know that the wallpaper colors have changed and what the new colors are, if that doesn't work, this part of the OS does not work correctly. Samsung also is a champion in making customizations to things like dynamic colors which completely break the expected behavior.
Can you tell me what happens when you set a static wallpaper (a photo or something like that) before you set Doodle as wallpaper? Remain the system colors the colors of the static wallpaper or are they also set to blue?

**Comment by Dafelleant** [comment]
> Thanks, that seems like multiple different issues. All in all I can say that the issues are caused by buggy customizations made by OnePlus to the original monet engine. A developer has exactly one official way to let the system know that the wallpaper colors have changed and what the new colors are, if that doesn't work, this part of the OS does not work correctly. Samsung also is a champion in making customizations to things like dynamic colors which completely break the expected behavior, but I thought OnePlus does a better job. Can you tell me what happens when you set a static wallpaper (a photo or something like that) before you set Doodle as wallpaper? Remain the system colors the colors of the static wallpaper or are they also set to blue?

No no, I'm using Lineage OS 19.1, there's aosp implementation of Monet. When I set static wallpaper colors being changed as it should be.

Last night at 03:00 wallpaper got randomized and colors switched to yellow as it should be. But if I enter Wallpaper & Style menu it will break colors until I re-set Doodle wallpaper.
