### ISSUE TITLE
Custom colors are not applied 

### ISSUE THREAD

**Issue by Faeryael** [patzly/doodle-android#72]
The custom colors I choose are not applied to the wallpaper.
When I set wallpaper after selecting custom colors, the default colors are applied.
Pixel4XL
Android 13
![Screenshot_20220906-150815](https://user-images.githubusercontent.com/112941891/188608578-04d52c7a-35ab-4d04-a5f1-3f490810236a.png)
![Screenshot_20220906-150819](https://user-images.githubusercontent.com/112941891/188608590-cbc82d29-9164-4a18-b693-1897d22a5331.png)

**Comment by patzly** [comment]
The label is "Extracted colors", not "Custom colors". Therefore it means that you can simply replace the default extracted colors from the wallpaper with other colors. When you tap on one of the three color circles, a dialog opens with an exact description on how these colors are used by the system.
The "extracted colors" feature is meant to be a fine-tuning if the default palette generates a theme that doesn't exactly match the user's preference or that doesn't exactly fit to the colors used in the wallpaper.
When you pay attention to system elements like buttons you will see that they use your color selection (especially the primary color) when Doodle is set as wallpaper, so it works as expected :)

**Comment by Faeryael** [comment]
> The label is "Extracted colors", not "Custom colors". Therefore it means that you can simply replace the default extracted colors from the wallpaper with other colors. When you tap on one of the three color circles, a dialog opens with an exact description on how these colors are used by the system. The "extracted colors" feature is meant to be a fine-tuning if the default palette generates a theme that doesn't exactly match the user's preference or that doesn't exactly fit to the colors used in the wallpaper. When you pay attention to system elements like buttons you will see that they use your color selection (especially the primary color) when Doodle is set as wallpaper, so it works as expected :)

So it doesn't actually change the wallpaper color of wallpaper only system elements?
![Screenshot_20220907-150309](https://user-images.githubusercontent.com/112941891/188851450-37d28b4d-18b7-429e-bbd6-8c4d43b2aff2.png)

**Comment by patzly** [comment]
Yes, the title of the dialog refers to the pre-set colors in the dialog. If the color you want is not among the provided colors, you tap on the last circle to choose a custom one. Does this make sense?

**Comment by Faeryael** [comment]
> Yes, the title of the dialog refers to the pre-set colors in the dialog. If the color you want is not among the provided colors, you tap on the last circle to choose a custom one. Does this make sense?

Yes, I chose custom color but that color is not applied to the wallpaper. Is it not suppose to be applied on wallpaper?
