### ISSUE TITLE
(Question) why doesn't the live wallpapers matches the size of google's

### ISSUE THREAD

**Issue by Seandylan123** [patzly/doodle-android#73]
![Screenshot_2022-09-10-10-56-49-662_dev wacko1805 pixel wallpapers](https://user-images.githubusercontent.com/106500241/189466323-41ba7876-0d2a-4625-b2dd-5c1dc36c0a57.jpg)
![Screenshot_2022-09-10-10-57-19-579_app lawnchair](https://user-images.githubusercontent.com/106500241/189466327-16c644ff-2de9-45d2-a5bf-a4c10f14a53e.jpg)

I just realized this here are some screenshots

**Comment by patzly** [comment]
Because the original scale was set once by the Google devs for the specific Pixel 4 devices the wallpaper was intended for to match their screen, but I can't set it to one specific size by default like them because my app is intended for every device, even for large-screen devices like tablets.
So I have written an algorithm that calculates the approximately best scale for your device depending on the screen size and display ratio. If it doesn't match exactly for you, then you can always change scale in the size section in Doodle settings.

**Comment by Seandylan123** [comment]
> Because the original scale was set once by the Google devs for the specific Pixel 4 devices the wallpaper was intended for to match their screen, but I can't set it to one specific size by default like them because my app is intended for every device, even for large-screen devices like tablets. So I have written an algorithm that calculates the approximately best scale for your device depending on the screen size and display ratio. If it doesn't match exactly for you, then you can always change scale in the size section in Doodle settings.

Ok thanks but what size is recommended for 392 dpi

**Comment by Seandylan123** [comment]
> I can't calculate this that easily and if so I would implement the correct algorithm... You can look on your own, you have the screenshots you sent and on them you can see how much you have to adjust the shape scale. The second is bigger than the original, so you simply decrease shape scale. Generally for scale unification on any device you can select the first doodle wallpaper and adjust shape size until the ring (on the middle right) matches the curved shape on the "moon" circle shape (below the ring) like on your the first screenshot. That would be the original scaling for Pixel4-sized phones, but for other sizes or tablets there is simply no right or wrong because the original pixel Doodle wallpapers were not optimized or ever intended for other devices.

Well setting it into 0.9 or 1.0 still doesn't match the moon on the middle right of the ring
![IMG_20220929_204735](https://user-images.githubusercontent.com/106500241/193035814-82e7955f-9cb8-491d-9800-f980befda6ce.jpg)
![IMG_20220929_204802](https://user-images.githubusercontent.com/106500241/193035876-b910fe84-8022-490e-8eb3-d38364d498d7.jpg)
Here's the screenshots

**Comment by patzly** [comment]
Where is the problem? Seems everything fine to me.. Why should it be the wrong size? Your screenshots look exactly like the original to me. As I said, there isn't really a "right or wrong" on devices other than Pixel 4 because the original wallpaper was only intended for this particular screen size.

**Comment by Seandylan123** [comment]
> Where is the problem? Seems everything fine to me.. Why should it be the wrong size? Your screenshots look exactly like the original to me. As I said, there isn't really a "right or wrong" on devices other than Pixel 4 because the original wallpaper was only intended for this particular screen size.

You have to look closer at the ring and that circular moon they don't align perfectly just almost and yes there is it a right or wrong on devices other than the pixel 4

**Comment by Seandylan123** [comment]
![IMG_20220930_093227](https://user-images.githubusercontent.com/106500241/193170899-c9bf0b33-f989-472a-9138-1bf52c71191f.jpg)
![IMG_20220930_093213](https://user-images.githubusercontent.com/106500241/193170904-23ef59ae-3ede-4038-bf47-316aded86621.jpg)
Here

**Comment by patzly** [comment]
That tiny difference should absolutely not disturb you... As I said, different screen sizes and densities result in different shape arrangements and sizes. Also the app is simply not a poor copy of the original but a totally different approach and project based on the design of the Pixel 4 Doodle wallpapers and others, so it should not be an issue if something (especially this tiny) is different to the original.
