### ISSUE TITLE
Random wallpaper daily does not work

### ISSUE THREAD

**Issue by MrVoid23** [patzly/doodle-android#74]
Since the latest version,changing the wallpaper at a certain time does not work correctly.I have tried uninstalling and deleting data and it's the same.Tried on different devices and same behavior.

When using random wallpaper at 3 am(any time) it works just fine the first day.It changes as it's supposed to.After the first day it does not change at all.

Should be an easy fix i assume?

**Comment by patzly** [comment]
Do you shutdown your device over night?

**Comment by MrVoid23** [comment]
I do not.It is charging while powered on.

**Comment by patzly** [comment]
Ok thanks I enabled daily random for me and tomorrow I can say whether it works for me or not.

**Comment by MrVoid23** [comment]
Sure,but it works the first day,not the other days

**Comment by patzly** [comment]
I have tried it and I think you are right... But I absolutely don't know what the problem is, hopefully I can solve it for the next update. Thank you!

**Comment by patzly** [comment]
Fixed in d8c810f78adc7b96d712138eca838221efc79771!
