### ISSUE TITLE
(Question) pixel 4a live wallpaper pinball?

### ISSUE THREAD

**Issue by Seandylan123** [patzly/doodle-android#76]
I'm not sure if this is possible but i'm not sure it's flat and 2d the only thing it can do is make the balls move when you swipe from your home screen or they move when you unlock your phone a tilt effect will also make these balls move(if enabled)

**Comment by Seandylan123** [comment]
I forgot to say doodle have the unlocking swiping and scrolling animation so i think it not really tricky to put them but it's not easy as expected as in the app title

**Comment by patzly** [comment]
Sorry, your English is very hard to understand and often doesn't really make sense. What should the app title have to do with the complexity of a new wallpaper?
And I sadly have to disappoint you, the Pinball wallpaper is not possible with the wallpaper engine of Doodle. The movement of a shape on a path is far too complex with the current engine.

**Comment by Seandylan123** [comment]
> Sorry, your English is very hard to understand and often doesn't really make sense. What should the app title have to do with the complexity of a new wallpaper? And I sadly have to disappoint you, the Pinball wallpaper is not possible with the wallpaper engine of Doodle. The movement of a shape on a path is far too complex with the current engine.

Oh sorry i didn't know it was far too complex with the current engine
