### ISSUE TITLE
Zoom animations when unlocking not working

### ISSUE THREAD

**Issue by Seandylan123** [patzly/doodle-android#79]
**Describe the bug**
I can't seem to find the zoom animations anymore when unlocking the phone

**To Reproduce**
1. Go to 'doodle'
2. Click on 'appearance then select any live wall'

**Expected behavior**
Zoom animation to working when unlocking

**Screenshots**

**Usage information (please complete the following):**
 - Device: [Xiaomi Redmi 9C]
 - OS: [Android 10 With stock miui rom]
 - Version [Latest]

**Comment by patzly** [comment]
Sorry, but your frequent issues are not very helpful and kind of annoying. As I said, it's often not clear what you mean and what you want. The issue template is meant as a structure template to replace all of the text with a clear description of your own issue, it doesn't make sense to let all the template text in there.
When the zoom effect is not working anymore, you can try to restart your phone and/or force-stop Doodle and apply it again as your wallpaper. Then it should work normally.
