### ISSUE TITLE
Set static background

### ISSUE THREAD

**Issue by EvadeMaster** [patzly/doodle-android#84]
#### **📜Additional information**
I'm sorry about my English, I'm not *fluent* in English, but I tried *and yes, I like to decorate using emojis.* I might improve this request but I'm busy at the moment.

#### **⚠️Problem**
I'm having a problem where I can't find a set static background prompt on a device running One UI, I always find myself having to visit [/app/src/main/res/raw](https://github.com/patzly/doodle-android/tree/master/app/src/main/res/raw), find the wallpaper of my choice, screenshot it, and set it as wallpaper just to change my colour palette because for some reason One UI doesn't properly get colour from Live wallpaper.

#### **🔧Suggestion**
I would suggest adding a set static background button in **Other options** settings, no matter which ROM are you using.

#### **📱Device Information**
Device: Samsung M23 5G
OS: One UI 4.1 (Android 12)
Version: Doodle 5.5.1

**Comment by patzly** [comment]
Hi, when you open Appearance settings, don't you see a card at the top with a button saying "Set static wallpaper"? This is the existing workaround for One UI users with Android 12 and higher.

If you don't see that card please tell me what Android version you have and maybe you can tell me the package name of the One UI Home launcher on your device, that would be helpful.

**Comment by EvadeMaster** [comment]
@patzly Yes, I don't see a card with a button to set static wallpaper, here are my Android & One UI Home version.

OS: Android 12 (One UI 4.1)
One UI Home: 13.1.09.3

**Comment by patzly** [comment]
Ok can you please send me a screenshot of the Appearance section?
And can you please install this app:
https://play.google.com/store/apps/details?id=com.stackbuffer.apkpackagenameviewer
Then please look for the One UI Home Launcher what its package name is. The correct package name is required for the card to appear, so I need the correct package name of the launcher and currently I'm not sure.

**Comment by EvadeMaster** [comment]
Here is my screenshot of the Appearance section, and my One UI Home package name is `com.sec.android.app.launcher`
![Screenshot_20221119-212733_Doodle.jpg](https://user-images.githubusercontent.com/93124920/202855736-dabab517-664b-4177-8c33-07115efa78aa.jpg)

**Comment by patzly** [comment]
Thanks! Please install this test build and let me know if the card is displayed:
(You have to rename the file ending from .zip to .apk because I can't upload apks here. Also you have to uninstall Doodle first because the test apk has another signature)

[Doodle-Android-v5.6.0-test1.zip](https://github.com/patzly/doodle-android/files/10047434/Doodle-Android-v5.6.0-test1.zip)

**Comment by EvadeMaster** [comment]
I have tested your test build, and the card is displayed, Tysm! 
![Screenshot_20221119-233740_Doodle.jpg](https://user-images.githubusercontent.com/93124920/202861698-c7445f86-4e08-4dcb-a120-6036ffabf24c.jpg)

**Comment by patzly** [comment]
That's amazing! Thank you for your help!
