### ISSUE TITLE
Ability to 'like' or 'favourite' currently generated wallpaper 

### ISSUE THREAD

**Issue by yashj9** [patzly/doodle-android#86]
Sometimes the color combinations and the style of wallpaper just hits different and you enjoy that set of wallpaper more compared to any other random combination.

I would not be wrong to guess that i am not alone who wishes this feature was there already and i am sure this feature will be very warmly welcomed by almost everyone.

I would like to have an option to be able to 'favourite' or 'like' or 'heart' the current wallpaper.

And that gets stored in a list of all the favorite wallpapers.

Ability to share such favourite wallpapers with other users would also be a very nice option. (Like it would be nice to share and set alike wallpapers between friend groups or partners)

Also to be able to cycle through your favourite wallpapers option would also be nice alongside the randomly generated new one. Such that the new wallpaper is always picked from the favourites only. (Like having a dedicated wallpaper for Monday, and or one for Friday, or just random from favourites also is fine)

Currently it is very hard to determine exactly what composition of the options has been applied to generate the currently applied wallpaper which makes it difficult to save a favourite preset even manually also.

I have already lost so many beautiful wallpapers, knowing that i may never get that exact combo ever again is just saddening sometimes. 😅

I love this project and this app is really very beautiful. Please help this feature get onboarded.

Let me know if any more info is required.

**Comment by patzly** [comment]
Thanks for your detailed issue but are you sure that you mean Doodle Android, the app developed by me? In this app, there aren't any options to generate new wallpapers, there are only specific designs you can pick from three categories. With this limited set of carefully created wallpapers it isn't possible to loose a wallpaper, you can always switch between them. For cycling through favourite wallpapers, you just need to enabled the "random wallpaper design" option and select an interval. Are you sure this is the right repository?

**Comment by yashj9** [comment]
@patzly, Yes, I agree that this has a limited set of combinations that get generated, but to be able to like or favorite seems like a good addition, right? 

Something that will store the pattern and color combination, so that the same can be reapplied later on.

**Comment by patzly** [comment]
@yashj9 No sorry, you're wrong, the wallpapers aren't generated. They will not change, so there is no need to store any color combination because you can simply select and reapply it again. Or just activate random mode and select your favoutite designs.

**Comment by yashj9** [comment]
Ow ok, understood. We may close this ticket then. Thanks for the clarification. 😊👍
