### ISSUE TITLE
Enormously high battery consumption in standbyl

### ISSUE THREAD

**Issue by Ruppi64** [patzly/doodle-android#87]
pixels 7
 Android 13
 Very high battery consumption in retirement
 Inclination angle On to minimum

**Comment by patzly** [comment]
That's not really a thing I can do domething against, it seems to be a random issue on your device as no other user has ever complained about battery usage... Maybe try reinstalling the app. What does high battery consumtion mean for you? The wallpaper only renders (and listens to tilting events) if it's visible so there shouldn't be any cause for high battery usage.

**Comment by Ruppi64** [comment]
Hello,it doesn't seem to go into deep sleep anymore! My quiescent current is significantly higher thanks to the app.I've done a clean install several times now and even rebooted my device.It's a shame because it's a great appBest regardsThomas Ruppert Gesendet von Mail für Windows Von: Patrick ZedlerGesendet: Dienstag, 7. Februar 2023 02:40An: patzly/doodle-androidCc: Ruppi64; AuthorBetreff: Re: [patzly/doodle-android] Enormously high battery consumption in standbyl (Issue #87) That's not really a thing I can do domething against, it seems to be a random issue on your device as no other user has ever complained about battery usage... Maybe try reinstalling the app. What does high battery consumtion mean for you? The wallpaper only renders (and listens to tilting events) if it's visible so there shouldn't be any cause for high battery usage.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by patzly** [comment]
@Ruppi64 Does the battery drain still occur if you install Doodle (with the latest Pixel updates installed)?

**Comment by Ruppi64** [comment]
Hello,yes it is now in the normal range. Even with the tilt turned on, it got better.Thanks! Gesendet von Mail für Windows Von: Patrick ZedlerGesendet: Donnerstag, 23. März 2023 01:22An: patzly/doodle-androidCc: Ruppi64; MentionBetreff: Re: [patzly/doodle-android] Enormously high battery consumption in standbyl (Issue ***@***.*** Does the battery drain still occur if you install Doodle (with the latest Pixel updates installed)?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by patzly** [comment]
Thank you very much! :)
