### ISSUE TITLE
"Follow system" only works if you open Doodle app

### ISSUE THREAD

**Issue by rodrigoswz** [patzly/doodle-android#9]
This issue started in v2.5.0, before the update it worked fine.

When changing the device's theme, the colors of the wallpaper remain the same. The colors will change only if you open Doodle app and then go back to homescreen.

Device: Xiaomi Mi 9T
Android: 11 (AOSP)
Doodle: 2.5.0 (from Google Play)

**Comment by patzly** [comment]
Hi, thanks for reporting and all the information! Funnily enough, I have the same smartphone as you :)
It's a bug I accidentally made yesterday when I remade the procedure of applying changes in the settings app to the wallpaper, I will fix it now.

**Comment by rodrigoswz** [comment]
Haha nice, thanks!

**Comment by patzly** [comment]
You're welcome, update with multiple new features and this fix is released! :)
